version: '3.4'

services:
  plwebdashboard:
    build:
      context: .
      dockerfile: src/Pl.Sas.WebDashboard/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Ho_Chi_Minh
      - ApplicationId=pl-webdashboard
      - SERVICE_PORTS=80
    ports:
      - "3406:80"
    restart: always
    networks:
      - pl-application-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  plscheduler:
    build:
      context: .
      dockerfile: src/Pl.Sas.Scheduler/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Ho_Chi_Minh
      - ApplicationId=pl-scheduler
      - SERVICE_PORTS=80
    ports:
      - "3407:80"
    restart: always
    networks:
      - pl-application-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  plwebstatus:
    build:
      context: .
      dockerfile: src/Pl.Sas.WebStatus/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Ho_Chi_Minh
      - ApplicationId=pl-webstatus
      - SERVICE_PORTS=80
    ports:
      - "3408:80"
    restart: always
    networks:
      - pl-application-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  plworker1:
    build:
      context: .
      dockerfile: src/Pl.Sas.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Ho_Chi_Minh
      - ApplicationId=pl-worker1
      - SERVICE_PORTS=80
    deploy:
      replicas: 4
    ports:
      - "3409-3413:80"
    restart: always
    networks:
      - pl-application-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

networks:
  pl-application-network:
    external:
      name: pl-network