name: application
on:
  push:
    branches:
    - application

jobs:
  application:
    runs-on: sasapp
    steps:
    - uses: actions/checkout@v3
    - name: docker-compose.yml up
      run: docker-compose -f docker-compose.yml -p pl_application up -d --build
  restarthaproxy:
    runs-on: sasapp
    steps:
    - name: restart ha-proxy
      run: docker restart pl_haproxy_plhaproxy_1
    needs: application
  clear:
    runs-on: sasapp
    steps:
    - name: delete source code
      run: rm -rf *
    - name: clean build cache file
      run: docker builder prune -a -f
    - name: clean all temp image
      run: docker image prune -f
    needs: restarthaproxy