name: haproxy
on:
  push:
    branches:
    - haproxy

jobs:
  haproxy:
    runs-on: sasapp
    steps:
    - uses: actions/checkout@v3
    - name: docker-compose-haproxy up
      run: docker-compose -f docker-compose-haproxy.yml -p pl_haproxy up -d --build
  clear:
    runs-on: sasapp
    steps:
    - name: delete source code
      run: rm -rf *
    - name: clean build cache file
      run: docker builder prune -a -f
    - name: clean all temp image
      run: docker image prune -f
    needs: haproxy