name: infrastructure
on:
  push:
    branches:
    - infrastructure

jobs:
  infastructure:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    #- name: infastructure up
    #  run: docker-compose -f docker-compose-infastructure.yml -p lab_infastructure up -d --build
  clear:
    runs-on: self-hosted
    steps:
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        path: /
    - name: clean build cache file
      run: docker builder prune -a -f
    - name: clean all temp image
      run: docker image prune -f
    needs: infastructure